/**
 * RSU Vest Types
 *
 * Defines types for RSU (Restricted Stock Unit) vest tracking
 */

export interface RsuVest {
  id: string
  user_id: string

  // Vest details
  vest_date: string
  shares_vested: number
  vest_price: number

  // Computed values (read-only, generated by database)
  total_gross_value: number

  // Sell-to-cover details
  sell_to_cover_shares: number
  sell_to_cover_value: number

  // Computed net value (read-only, generated by database)
  net_value: number

  // Goal allocation
  goal_contribution_id: string | null

  // Additional info
  company_name: string | null
  notes: string | null

  // Metadata
  created_at: string
  updated_at: string
}

// Insert type omits computed fields and auto-generated fields
export type RsuVestInsert = Omit<
  RsuVest,
  'id' | 'total_gross_value' | 'net_value' | 'created_at' | 'updated_at'
>

// Update type for partial updates
export type RsuVestUpdate = Partial<
  Omit<RsuVest, 'id' | 'user_id' | 'total_gross_value' | 'net_value' | 'created_at' | 'updated_at'>
>

// Goal contribution source types (matches database constraint)
export type GoalContributionSource =
  | 'manual'
  | 'paystub'
  | 'transfer'
  | 'interest'
  | 'rsu_vest'
  | 'espp_purchase'

// Extended goal contribution type with RSU support
export interface GoalContribution {
  id: string
  goal_id: string
  amount: number
  contribution_date: string
  source: GoalContributionSource
  paystub_id: string | null
  rsu_vest_id: string | null
  notes: string | null
  created_at: string
}

export type GoalContributionInsert = Omit<GoalContribution, 'id' | 'created_at'>
